force-app/main/default/objects/Mix__c/Mix__c.object-meta.xml
<CustomObject>
    <description>A custom collection of tracks for a customer.</description>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Mix__c/fields/Primary_Genre__c.field-meta.xml
<CustomField>
    <fullName>Primary_Genre__c</fullName>
    <description>Primary genre of the mix.</description>
    <label>Primary Genre</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <description>Songs from new and classic artists.</description>
    <label>Song</label>
    <nameField>
        <label>Song  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>Genre of the song.</description>
    <label>Genre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Pop</fullName>
            </value>
            <value>
                <fullName>Jazz</fullName>
            </value>
            <value>
                <fullName>Rap</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Song__c/fields/Track_Count__c.field-meta.xml
<CustomField>
    <fullName>Track_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of times a song is used as a track.</description>
    <label>Track Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Track Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Mix__c.field-meta.xml
<CustomField>
    <fullName>Mix__c</fullName>
    <description>Mix this track is part of.</description>
    <label>Mix</label>
    <referenceTo>Mix__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Track__c/fields/Song__c.field-meta.xml
<CustomField>
    <fullName>Song__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Song for this track.</description>
    <label>Song</label>
    <referenceTo>Song__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TrackTriggerHelper.cls
public with sharing class TrackTriggerHelper 
{
    public static void setGenres(List<Track__c> trackList) 
    {
        Set<Id> mixIds = new Set<Id>();

        for(Track__c currentTrack : trackList)
        {
            mixIds.add(currentTrack.Mix__c);
        }

        Map<Id, Mix__c> mixToUpdate = new Map<Id, Mix__c>();

        List<AggregateResult> aggregateResults = 
        [
            SELECT Mix__r.Id Id, Song__r.Genre__c songGenre, count(Id) 
            FROM Track__c 
            WHERE Mix__r.Id IN :mixIds
            GROUP BY Mix__r.Id, Song__r.Genre__c
            ORDER BY Mix__r.Id, count(Id) DESC
        ];

        for(AggregateResult currentAR : aggregateResults)
        {
            if(!mixToUpdate.containsKey((Id)currentAR.get('Id')))
            {
                mixToUpdate.put((Id)currentAR.get('Id'), new Mix__c(Id = (Id)currentAR.get('Id')));
            }
            if(mixToUpdate.get((Id)currentAR.get('Id')).Primary_Genre__c == null)
            {
                mixToUpdate.get((Id)currentAR.get('Id')).Primary_Genre__c = (String)currentAR.get('songGenre');
                continue;
            }
            else if(mixToUpdate.get((Id)currentAR.get('Id')).Secondary_Genre__c == null)
            {
                mixToUpdate.get((Id)currentAR.get('Id')).Secondary_Genre__c = (String)currentAR.get('songGenre');
                continue;
            }
            continue;    
        }
        
        if(!mixToUpdate.isEmpty())
        {
            update mixToUpdate.values();
        }
    }

    public static void setTrackCount(List<Track__c> trackList) 
    {
        List<Song__c> songsToUpdate = new List<Song__c>();

        Set<Id> songIds = new Set<Id>();

        for(Track__c currentTrack : trackList)
        {
            songIds.add(currentTrack.Song__c);
        }

        List<AggregateResult> aggregateResults = 
        [
            SELECT Song__r.Id songId, count(Id) trackCount 
            FROM Track__c 
            WHERE Song__r.Id IN :songIds 
            GROUP BY Song__r.Id
        ];
        
        for(AggregateResult currentAR : aggregateResults)
        {
            songsToUpdate.add(new Song__c(Id =(Id)currentAR.get('songId'), Track_Count__c = (Integer)currentAR.get('trackCount')));
        }

        if(!songsToUpdate.isEmpty())
        {
            update songsToUpdate;
        }
    }
}