force-app/main/default/objects/Mix__c/Mix__c.object-meta.xml
<CustomObject>
    <description>A custom collection of tracks for a customer.</description>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Mix__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact purchasing the mix.</description>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mixes</relationshipLabel>
    <relationshipName>Mixes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <description>Songs from new and classic artists.</description>
    <label>Song</label>
    <nameField>
        <label>Song  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>Genre of the song.</description>
    <label>Genre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Pop</fullName>
            </value>
            <value>
                <fullName>Jazz</fullName>
            </value>
            <value>
                <fullName>Rap</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Song__c/fields/Length_m__c.field-meta.xml
<CustomField>
    <fullName>Length_m__c</fullName>
    <description>Length of the song in minutes.</description>
    <label>Length (m)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Track Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Mix__c.field-meta.xml
<CustomField>
    <fullName>Mix__c</fullName>
    <description>Mix this track is part of.</description>
    <label>Mix</label>
    <referenceTo>Mix__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Track__c/fields/Song__c.field-meta.xml
<CustomField>
    <fullName>Song__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Song for this track.</description>
    <label>Song</label>
    <referenceTo>Song__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MixBuilderControllerTest.cls
@isTest
private class MixBuilderControllerTest 
{
    @TestSetup
    static void makeData()
    {
        List<Song__c> songs = TestFactory.createSongs(20);
        List<Mix__c> mixes = TestFactory.createMixes(5);
        List<Track__c> tracks = new List<Track__c>();

        insert mixes;
        insert songs;

        TestFactory.createTracks(songs, mixes[0]);
        TestFactory.createTracks(songs, mixes[1]);

        insert tracks;
    }

    @isTest
    static void testMixInsert()
    {
        List<Song__c> songs = [SELECT Id, Name, Genre__c, Length_m__c FROM Song__c];
        Mix__c mix = new Mix__c();
        List<Track__c> tracksToInsert = new List<Track__c>();

        Track__c newTrack = new Track__c();
        tracksToInsert.add(newTrack);

        Test.startTest();

        PageReference pageRef = Page.MixBuilder;
        Test.setCurrentPage(pageRef);

        ApexPages.StandardController sc = new ApexPages.StandardController(mix);
        MixBuilderController extension = new MixBuilderController(sc);
        extension.resetSetCon();
        extension.getWrapperRecordList();
        extension.getMapHoldingSelectedRecords();
        extension.getGenres();
        extension.save();
        extension.doCancel();
      
        Test.stopTest();
    }

    @isTest
    static void testMixUpdate()
    {
        List<Song__c> songs = [SELECT Id, Name, Genre__c, Length_m__c FROM Song__c]; 
        List<Mix__c> mix = [SELECT Id, Name, Customer__c FROM Mix__c];
        List<Track__c> tracksInMix = [SELECT Id, Song__c, Mix__c FROM Track__c WHERE Mix__c = :mix[0].Id];
        List<Track__c> tracksToInsert = new List<Track__c>();
        List<Track__c> tracksToDelete = [SELECT Id FROM Track__c];

        Track__c newTrack = new Track__c();
        tracksToInsert.add(newTrack);
        // tracksToDelete.remove[0];

        
        
        Test.startTest();

        PageReference pageRef = Page.MixBuilder;
        Test.setCurrentPage(pageRef);

        pageRef.getParameters().put('id', (String)mix[0].id);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(mix[0]);
        MixBuilderController extension = new MixBuilderController(sc);

        extension.getWrapperRecordList();
        extension.getMapHoldingSelectedRecords();
        extension.getGenres();
        extension.save();
        extension.doCancel();

        Test.stopTest();
    }

}