force-app/main/default/objects/Mix__c/Mix__c.object-meta.xml
<CustomObject>
    <description>A custom collection of tracks for a customer.</description>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <description>Songs from new and classic artists.</description>
    <label>Song</label>
    <nameField>
        <label>Song  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Artist__c.field-meta.xml
<CustomField>
    <fullName>Artist__c</fullName>
    <description>Name of the artist.</description>
    <label>Artist</label>
    <length>180</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Song__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>Genre of the song.</description>
    <label>Genre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Pop</fullName>
            </value>
            <value>
                <fullName>Jazz</fullName>
            </value>
            <value>
                <fullName>Rap</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Song__c/fields/Length_m__c.field-meta.xml
<CustomField>
    <fullName>Length_m__c</fullName>
    <description>Length of the song in minutes.</description>
    <label>Length (m)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Song__c/fields/Track_Count__c.field-meta.xml
<CustomField>
    <fullName>Track_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of times a song is used as a track.</description>
    <label>Track Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Song__c/fields/Track_Licenses__c.field-meta.xml
<CustomField>
    <fullName>Track_Licenses__c</fullName>
    <description>Number of times CCV is licensed to include the song in a mix.</description>
    <label>Track Licenses</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Track Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Mix__c.field-meta.xml
<CustomField>
    <fullName>Mix__c</fullName>
    <description>Mix this track is part of.</description>
    <label>Mix</label>
    <referenceTo>Mix__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Track__c/fields/Song__c.field-meta.xml
<CustomField>
    <fullName>Song__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Song for this track.</description>
    <label>Song</label>
    <referenceTo>Song__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestFactory.cls
@isTest
public with sharing class TestFactory 
{
    public static List<Mix__c> createMixes(Integer mixCount) 
    {
        List<Mix__c> mixList = new List<Mix__c>();
        for(Integer i = 0; i < mixCount; i++)
        {
            mixList.add(new Mix__c(Name = 'Mix ' + i));
        }
        return mixList;
    }

    public static List<Song__c> createSongs(Integer songCount)
    {
        List<Song__c> songList = new List<Song__c>();
        for(Integer i = 0; i < songCount; i++)
        {
            songList.add(new Song__c(
                                    Name = 'Song ' + i,  
                                    Artist__c = 'Artist ' + i, 
                                    Length_m__c = 3, Track_Count__c = 0, 
                                    Track_Licenses__c = 5));

            if(math.mod(i, 2) == 0)
            {
                songList[i].Genre__c = 'Pop';
            } else
            {
                songList[i].Genre__c = 'Rap';
            }
        }
        return songList;
    }

    public static List<Track__c> createTracks(List<Song__c> songList, Mix__c mix)
    {
        List<Track__c> trackList = new List<Track__c>();
        for(Song__c currentSong : songList)
        {
            trackList.add(new Track__c(Song__c = currentSong.Id, Mix__c = mix.Id));
        }     
        return trackList;
    }
}