force-app/main/default/objects/Mix__c/Mix__c.object-meta.xml
<CustomObject>
    <description>A custom collection of tracks for a customer.</description>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <description>Songs from new and classic artists.</description>
    <label>Song</label>
    <nameField>
        <label>Song  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>Genre of the song.</description>
    <label>Genre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Pop</fullName>
            </value>
            <value>
                <fullName>Jazz</fullName>
            </value>
            <value>
                <fullName>Rap</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Track Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Mix__c.field-meta.xml
<CustomField>
    <fullName>Mix__c</fullName>
    <description>Mix this track is part of.</description>
    <label>Mix</label>
    <referenceTo>Mix__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Track__c/fields/Song__c.field-meta.xml
<CustomField>
    <fullName>Song__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Song for this track.</description>
    <label>Song</label>
    <referenceTo>Song__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TrackTriggerTest.cls
@isTest
private class TrackTriggerTest 
{
    @TestSetup
    static void makeData()
    {
        List<Song__c> songs = TestFactory.createSongs(20);
        List<Mix__c> mixes = TestFactory.createMixes(5);
        List<Track__c> tracks = new List<Track__c>();

        insert mixes;
        insert songs;

        TestFactory.createTracks(songs, mixes[0]);
        TestFactory.createTracks(songs, mixes[1]);

        insert tracks;
    }


    @isTest
    static void testBulkInsert() 
    {
        List<Mix__c> mixes = [SELECT Id FROM Mix__c];
        List<Song__c> songs = [SELECT Id FROM Song__c LIMIT 10];
        List<Track__c> newTracks = TestFactory.createTracks(songs, mixes[2]);

        Test.startTest();
        insert newTracks;
        Test.stopTest();
    }

    @isTest
    static void testBulkUpdate()
    {
        List<Mix__c> mixes = [SELECT Id FROM Mix__c OFFSET 3];
        List<Track__c> tracksToUpdate = [SELECT Id FROM Track__c LIMIT 10];
        for(Track__c currentTrack : tracksToUpdate)
        {
            currentTrack.Mix__c = mixes[0].Id;
        }

        Test.startTest();
        update tracksToUpdate;
        Test.stopTest();
    }

    @isTest
    static void testBulkDelete()
    {
        List<Track__c> tracks = [SELECT Id 
                                FROM Track__c 
                                WHERE Song__r.Genre__c = 'Rap' 
                                LIMIT 10];

        Test.startTest();
        delete tracks;
        Test.stopTest();     
    }
}